name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run Rubocop
      run: bundle exec rubocop
    - name: Run tests
      run: bundle exec rake spec
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: coverage
    - name: github actions notify to slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventname,ref,workflow,job,took
        mention: 'here'
        if_mention: failure
      env:
        github_token: ${{ github.token }}
        slack_webhook_url: ${{ secrets.slack_webhook_url }}
        matrix_context: ${{ tojson(matrix) }}
      if: always()
